FROM node:20.9.0

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# ENV PORT를 사용하는 이유는 next js default port가 3000이기 때문에 4000으로 변경
ENV PORT=4000 

EXPOSE 4000

CMD [ "npm", "run", "start" ]
